version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "service-portal-user-front-prod"
          ContainerPort: 3000
        # Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["subnet-0dda213e98b653a32","subnet-0e61b1d029e553ac2"]
            SecurityGroups: ["sg-02037b9aaa6e8f2f4"]
            AssignPublicIp: "FALSE"
        CapacityProviderStrategy:
          - Base: 1
            CapacityProvider: "FARGATE_SPOT"
            Weight: 2
          - Base: 0
            CapacityProvider: "FARGATE"
            Weight: 1

#Hooks:
#  - BeforeInstall: "LambdaFunctionToValidateBeforeInstall"
#  - AfterInstall: "LambdaFunctionToValidateAfterInstall"
#  - AfterAllowTestTraffic: "LambdaFunctionToValidateAfterTestTrafficStarts"
#  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeAllowingProductionTraffic"
#  - AfterAllowTraffic: "LambdaFunctionToValidateAfterAllowingProductionTraffic"
